language: python
env:
  OMP_NUM_THREADS: 4

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.5
          env: TOXENV=py35
        - os: linux
          sudo: required
          python: 3.6
          env: TOXENV=py36
        - os: osx
          language: generic
          env: TOXENV=py35
        - os: osx
          language: generic
          env: TOXENV=py36
install:
    - ./.travis/install.sh
script:
  - tox
  - tox -e checkstyle
  - tox -e testcov
  - tox -e lint
  - tox -e checktypes
  - tox -e docs
