language: python
env:
  OMP_NUM_THREADS: 4

matrix:
    include:
        - python: 3.5
        - python: 3.6
        - os: osx
          language: generic
          env: TOXENV=py35
        - os: osx
          language: generic
          env: TOXENV=py36
install:
    - bash .travis/install.sh
script:
    - bash .travis/run.sh
