os:
  - linux
  - osx
language: python
python:
  - "3.5"
  - "3.6"
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;bash miniconda.sh -b -p $HOME/miniconda; export PATH="$HOME/miniconda/bin:$PATH" ;  fi
  - pip install tox-travis
script:
  - tox
  - tox -e checkstyle
  - tox -e testcov
  - tox -e lint
  - tox -e checktypes
  - tox -e docs
env:
  OMP_NUM_THREADS: 4
