language: python
env:
  OMP_NUM_THREADS: 4

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.2
          env: TOXENV=py32
        - os: linux
          sudo: required
          python: 3.3
          env: TOXENV=py33
        - os: osx
          language: generic
          env: TOXENV=py32
        - os: osx
          language: generic
          env: TOXENV=py33
install:
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install python3; pip3 install tox-travis; else pip install tox-travis; fi
script:
  - tox
  - tox -e checkstyle
  - tox -e testcov
  - tox -e lint
  - tox -e checktypes
  - tox -e docs
